### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by zetchan**
Added spanish translation for this plugin.
Everything in the .pot translated except some URLs and names.
There are some texts still appearing in english in WP because they are missing in the pot file, like:
"Show # entries", "Showing # to # of # entries", "Search" and some options.

Thank you for this plugin!

### CODE REVIEW

**Comment by Sudavar** [comment]
That's great :D thank you very much. 
I will add the translation tomorrow as now I am home and already closed my systems.
Now it is also possible to use GlotPress mechanism for the widget's translation (https://translate.wordpress.org/projects/wp-plugins/birthdays-widget) but I haven't tested much around yet.

**Comment by Sudavar** [comment]
As far as the texts you mentioned are concerned they are mostly part of a 3rd party plugin ([Datatables](https://www.datatables.net/) ) which is written in JS and does not support .pot translations by default... Will have to take a look

**Comment by zetchan** [comment]
Sorry, didn't saw that translation page... If you want I can check it before merging and trying to do it that way so anyone could check and fix my translation.

**Comment by Sudavar** [comment]
It's a bit tricky I suspect, because there was no Spanish translation made until now, so think the percentage is just strings matched from the whole WordPress translation... Will have to investigate a bit more.

**Comment by zetchan** [comment]
I'm cancelling the pull request and will check/do the other translation system. I've just saw that in the today release (1.7.1) there are new strings missing on my translation. Thank you for your answers and sorry for the trouble.

**Pull request closed without merging**
